//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundStudio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int id_app { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<int> app_type { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> app_status { get; set; }
    
        public virtual ApplicationStatuses ApplicationStatuses { get; set; }
        public virtual ApplicationTypes ApplicationTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
